apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  alert-rules.yml: |
    groups:
    - name: transformation-engine-alerts
      rules:
      - alert: HighErrorRate
        expr: sum(rate(transformation_engine_errors_total[5m])) / sum(rate(transformation_engine_transformations_total[5m])) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate in Transformation Engine"
          description: "Transformation Engine has a high error rate (> 10%) for the last 5 minutes"

      - alert: LowVerificationSuccessRate
        expr: transformation_engine_verification_success_ratio < 0.8
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Low verification success rate"
          description: "Transformation verification success rate is below 80% for the last 10 minutes"

      - alert: SlowTransformations
        expr: histogram_quantile(0.95, sum(rate(transformation_engine_transformation_duration_seconds_bucket[10m])) by (le)) > 30
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Slow transformations detected"
          description: "95th percentile of transformation duration is above 30 seconds for the last 10 minutes"

      - alert: TransformationEngineDown
        expr: up{job="transformation-engine"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Transformation Engine is down"
          description: "Transformation Engine has been down for more than 1 minute"

      - alert: HighMemoryUsage
        expr: container_memory_usage_bytes{container="transformation-engine"} / container_spec_memory_limit_bytes{container="transformation-engine"} > 0.85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage in Transformation Engine"
          description: "Transformation Engine is using more than 85% of its memory limit for the last 5 minutes"

      - alert: HighCPUUsage
        expr: sum(rate(container_cpu_usage_seconds_total{container="transformation-engine"}[5m])) / sum(container_spec_cpu_quota{container="transformation-engine"} / 100000) > 0.85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage in Transformation Engine"
          description: "Transformation Engine is using more than 85% of its CPU limit for the last 5 minutes"
