apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transformation-engine-workspace-pvc
  namespace: code-analysis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
