apiVersion: v1
kind: Secret
metadata:
  name: transformation-engine-secrets
  namespace: code-analysis
type: Opaque
data:
  # These are base64 encoded placeholders - replace with actual values
  mongo_uri: bW9uZ29kYjovL3VzZXJuYW1lOnBhc3N3b3JkQGhvc3Q6cG9ydC9kYXRhYmFzZQ==  # mongodb://username:password@host:port/database
  # GitHub credentials
  github_token: Z2hwX3lvdXJfdG9rZW5faGVyZQ==  # Replace with base64 encoded GitHub token
  git_username: dXNlcm5hbWU=  # Replace with base64 encoded GitHub username
  # Add other secrets as needed
